name: Deploy to server LightSail TurnoFarm

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          NODE_OPTIONS: '--max-old-space-size=4096 --openssl-legacy-provider'
        run: npm run build

      - name: Archive build files
        run: tar -czf build.tar.gz build

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: build.tar.gz
          target: /home/bitnami/htdocs/

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          key_type: pem
          port: 22
          script: |
            cd /home/bitnami/htdocs/
            tar -xzf build.tar.gz
            cp -r build/* /opt/bitnami/apache/htdocs/
            rm -rf build.tar.gz build