name: Deploy to server LightSail

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          key_type: pem
          port: 22
          script: |
            cd /home/bitnami/htdocs/frontend-impch-zanartu
            git clean -f
            git pull origin main
            npm install --only=prod
            echo NEXT_PUBLIC_URL=localhost:4000 > .env
            echo NEXT_PUBLIC_PATHLOGIN=/auth/login >>.env
            echo NEXT_PUBLIC_PATCHGRAPHQL=/graphql >>.env
            pm2 delete frontend-impch
            pm2 list
            pm2 start npm --name "frontend-impch" -- start
