name: Deploy to server LightSail Impch Zanartu Frontend

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          key_type: pem
          port: 22
          script: |
            cd /home/bitnami/paginas/frontend-impch-zanartu
            echo NEXT_PUBLIC_URL=https://app.impchzanartu.online > .env
            echo NEXT_PUBLIC_PATHLOGIN=/auth/login >>.env
            echo NEXT_PUBLIC_PATCHGRAPHQL=/graphql >>.env
            git clean -f
            git pull origin main
            npm ci
            npm run build
            pm2 restart frontend-impch-zanartu

