name: Deploy to server LightSail TurnoFarm

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          key_type: pem
          port: 22
          script: |
            cd /home/bitnami/paginas/frontend-impch-zanartu
            echo NEXT_PUBLIC_URL=localhost:4000 > .env
            echo NEXT_PUBLIC_PATHLOGIN=/auth/login >>.env
            echo NEXT_PUBLIC_PATCHGRAPHQL=/graphql >>.env
            echo NEXT_PUBLIC_PATCHGRAPHQL=/graphql >>.env
            npm install
            npm run build
            pm2 stop frontend-impch-zanartu
            pm2 restart frontend-impch-zanartu

